from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum
from database import Base

class NewsStatus(str, enum.Enum):
    NEW = "NEW"
    IN_QUEUE = "IN_QUEUE"
    GENERATING = "GENERATING"
    READY = "READY"
    ERROR = "ERROR"
    PUBLISHED = "PUBLISHED"

class VideoFormat(str, enum.Enum):
    VERTICAL = "VERTICAL"
    HORIZONTAL = "HORIZONTAL"
    SQUARE = "SQUARE"

class Project(Base):
    __tablename__ = "projects"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    settings = relationship("GlobalSettings", back_populates="project")
    sources = relationship("RssSource", back_populates="project")
    news_items = relationship("NewsItem", back_populates="project")
    tasks = relationship("VideoTask", back_populates="project")

class GlobalSettings(Base):
    __tablename__ = "global_settings"
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), default=1)
    key = Column(String, index=True)
    value = Column(String)
    
    project = relationship("Project", back_populates="settings")

class RssSource(Base):
    __tablename__ = "rss_sources"
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), default=1)
    name = Column(String, index=True)
    url = Column(String, index=True) # Removed unique=True to allow same RSS in different projects
    is_active = Column(Boolean, default=True)
    is_aggregator = Column(Boolean, default=False)
    
    project = relationship("Project", back_populates="sources")
    news_items = relationship("NewsItem", back_populates="source")

class NewsItem(Base):
    __tablename__ = "news_items"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), default=1)
    source_id = Column(Integer, ForeignKey("rss_sources.id"), nullable=True)
    title = Column(String, index=True)
    link = Column(String, index=True) # Removed unique=True to allow same news in different projects
    description = Column(Text)
    full_text = Column(Text, nullable=True)
    source_url = Column(String, nullable=True)
    pub_date = Column(DateTime, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    status = Column(String, default=NewsStatus.NEW.value)
    
    project = relationship("Project", back_populates="news_items")
    source = relationship("RssSource", back_populates="news_items")
    task = relationship("VideoTask", back_populates="news", uselist=False)

class VideoTask(Base):
    __tablename__ = "video_tasks"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), default=1)
    news_id = Column(Integer, ForeignKey("news_items.id"))
    prompt = Column(Text, nullable=True)
    voice = Column(String, default="female") # generic female voice by default
    image_search_engine = Column(String, default="yandex")
    video_format = Column(String, default=VideoFormat.VERTICAL.value)
    duration = Column(Integer, default=30)
    background_music = Column(String, nullable=True) # file path or name
    music_volume = Column(Integer, default=30) # Volume percentage 0-100
    image_zoom = Column(Integer, default=5) # Ken Burns zoom percentage (e.g. 5 means 100% to 105%)
    watermark_path = Column(String, nullable=True) # file path or name
    source_url = Column(String, nullable=True)
    delete_temp_files = Column(Boolean, nullable=True)
    
    # Togglable logic overrides (from project settings at creation time)
    use_rewrite = Column(Boolean, default=True)
    use_seo = Column(Boolean, default=True)
    use_cta = Column(Boolean, default=False)
    
    # Metadata (initially generated by LLM, editable in UI)
    video_title = Column(String, nullable=True)
    custom_title = Column(String, nullable=True)
    video_description = Column(Text, nullable=True)
    video_tags = Column(String, nullable=True) # Comma-separated tags
    image_keywords = Column(String, nullable=True) # Comma-separated keywords for image search
    target_platforms = Column(String, nullable=True) # JSON array like ["youtube", "telegram"]
    
    error_message = Column(Text, nullable=True)
    video_path = Column(String, nullable=True)
    status = Column(String, default="NEW") # NEW, READY, PUBLISHED
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    project = relationship("Project", back_populates="tasks")
    news = relationship("NewsItem", back_populates="task")
